name: GitHub Actions Secret Example

on:
  push:
    branches: [ main ]

jobs:
  secrets-in-github-actions:
    runs-on: windows-latest

    # The Secrect Actions GitHub example has three steps
    steps:
      # Show how to print unmasked GitHub secrets to the console
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.DB_PORT }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.DB_PORT}} | sed 's/./& /g' 

      # Use a GitHub Actions secret variable in a bash shell
      - name: Step 2 - GitHub Action if statement (true)
        env: 
          DB_PORT: ${{ secrets.DB_PORT }}
        if:  env.DB_PORT == '3307'
        run: echo "I know what the secret token is!"

      # A GitHub Actions if statement with a secret environment variable
      - name: Step 3 - Conditional GitHub Action (false)
        shell: bash
        env: 
          DB_PORT: ${{ secrets.DB_PORT }}
        if:  env.DB_PORT != '3307'
        run: echo "I was wrong thinking the GitHub secret was '3307'!"

