# This is a basic workflow that is manually triggered

name: Test Secrets

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name: Step 2 - GitHub Action if statement (true)
    env: 
      DB_PORT: ${{ secrets.DB_PORT }}
    if:  env.DB_PORT == '3307'
    run: echo "DB_PORT is right!"
